### ISSUE TITLE
Error on XMLHttpRequest after including f-twelve in angular application

### ISSUE THREAD

**Issue by sankp** [cerner/f-twelve#58]
Error: Failed to set the 'responseType' property on 'XMLHttpRequest': The response type cannot be changed for synchronous requests made from a document.

![image](https://user-images.githubusercontent.com/9613276/116152308-5aec8300-a6ab-11eb-99b2-d8040dc1ce7e.png)

Check this image where network calls are blocked with above error.
![image](https://user-images.githubusercontent.com/9613276/116153196-8cb21980-a6ac-11eb-9924-9b087c15d2c1.png)

**Comment by pgross41** [comment]
@sankp `sockjs-node` is that a web socket? I have never tested this with web sockets. 

Unrelated idea: there should be a way to disable the different tabs in case they interfere while still being able to use the working tabs. It won't fix your Network tab but at least you'd still be able to use the Console tab. 🙂

**Comment by sankp** [comment]
@pgross41 Is network tab is the issue or any XMLHttpRequest request getting blocked is the issue ? how to disable network tab ?

**Comment by pgross41** [comment]
@sankp is f-twelve causing the error? If yes then it is possible it's doing something that the XMLHttpRequest doesn't like. This is the only place `responseType` is used in the code but it's not writing to xhr it's only reading. 
https://github.com/cerner/f-twelve/blob/e9474c2c970493b231242560aced19848c828ae0/src/components/useNetworkData.js#L47-L49

I have not seen this error before so I will need more info to recreate and troubleshoot. Can you confirm f-twelve is causing the error and is this a web socket connection that causes the error?

**Comment by sankp** [comment]
yes @pgross41 after adding f-twelve it started giving this error. Application is using angular, rx-js, observables etc.

**Comment by pgross41** [comment]
Okay I'll take a look and let you know what I find

**Comment by sankp** [comment]
Sure @pgross41 let me know what you find.

**Comment by sankp** [comment]
@pgross41 we deployed this test app on our servers and tried accessing it from Cerner Millennium enviornment. Its not showing above error there but while making an api it's not able to find base href which is supposed to be domainname/application/api/controller/getaction but instead it takes /api/controller/getaction. So we have 2 different behaviors now. I am happy to setup WebEx call with you and show.

**Comment by pgross41** [comment]
I am available until 5 if you want to webex. My email is my username at gmail.

**Comment by pgross41** [comment]
@sankp actually that was a lie, I am not available today but I could do tomorrow anytime after 11.

**Comment by sankp** [comment]
sure @pgross41 I have setup for tomorrow 11 am.

**Comment by sankp** [comment]
@pgross41 is there a way to check if app is running from Cerner Millennium so that we can include this library conditionally?

**Comment by pgross41** [comment]
@sankp  yes, we use this: 
```js
isPowerChart: () => (window.external && typeof window.external.DiscernObjectFactory !== 'undefined')
```

Also I am looking into the idea of providing the ability to disable specific tabs. All the console/network hooks are enabled by default so we first need to confirm that disabling them after they've already been enabled will avoid the error. If you call fTwelve.disable() right after importing it does it prevent the error? Example: 

```js
import fTwelve from 'f-twelve';
fTwelve.disable();
```

**Comment by sankp** [comment]
Hi @pgross41 Thanks for this help. We were able to make this working in Powerchart now. I configured it conditionally so on localhost it will not be enable so all XMLHttpRequest  will work. In Powerchart it's enabled so it will work properly over there.

**Comment by pgross41** [comment]
I'm glad you found a solution that allows it work with your configuration. Closing issue.
