### ISSUE TITLE
archive this project

### ISSUE THREAD

**Issue by sambao21** [cerner/f-twelve#87]
Due to the inactivity of this project for over 1 year, this project is marked to be archived at end of January 2024. Previously release assets will be untouched, but support will cease for this project going forward. If anyone has any reasons this project should not be archived, please comment.

**Comment by pgross41** [comment]
Farewell, f-twelve 🫡

**Comment by Letter3** [comment]
We can move this to inner sourced for now, we still use this project internally

**Comment by sambao21** [comment]
@Letter3 we will archive this then, and you can fork it internally.
